title: Daniel Rotter
lang: en
description: A blog about web development in general and about PHP, JavaScript, Linux and its command line in particular.

author:
    twitter: danrot90

social:
    name: Daniel Rotter
    links:
        - https://twitter.com/danrot90
        - https://www.linkedin.com/in/daniel-rotter-ba634859/
        - https://github.com/danrot
        - https://stackoverflow.com/users/1292378/daniel-rotter

twitter:
    username: danrot90
    card: summary

feed:
    excerpt_only: true

plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
